import { AustralianState, speciesType } from "~/types/mainTypes";

export const speciesByState: Record<AustralianState, speciesType[]> = {
    '': [],
    NT: [
      { name: 'Barramundi', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Mackerel', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Threadfin Salmon', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Mangrove Jack', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Golden Snapper', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Black Jewfish', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Queenfish', eatingRating: 3, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Giant Trevally', eatingRating: 2, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Coral Trout', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Red Emperor', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Spanish Mackerel', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Blue Salmon', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Gold-Spotted Rockcod', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Cod', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Mud Crab', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    SA: [
      { name: 'Snapper', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Gummy Shark', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'King George Whiting', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Flathead', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Mulloway', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Salmon', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Australian Herring', eatingRating: 3, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Blue Swimmer Crab', eatingRating: 5, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Southern Calamari', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Silver Trevally', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Whiting', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Yellowfin Tuna', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Sand Whiting', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Leatherjacket', eatingRating: 3, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Samson Fish', eatingRating: 3, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    NSW: [
      { name: 'Mulloway', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Yellowtail Kingfish', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Snapper', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Bream', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Dusky Flathead', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Luderick', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Silver Trevally', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Whiting', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Blackfish', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Sand Whiting', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Australian Salmon', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Kingfish', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Blue Groper', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Bonito', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Leatherjacket', eatingRating: 3, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    VIC: [
      { name: 'Brown Trout', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Rainbow Trout', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Redfin Perch', eatingRating: 3, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Snapper', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'King George Whiting', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Australian Salmon', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Silver Trevally', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Flathead', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Luderick', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Leatherjacket', eatingRating: 3, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Garfish', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Whiting', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Bream', eatingRating: 3, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Blue Warehou', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
      { name: 'Gummy Shark', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    QLD: [
        { name: 'Coral Trout', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Spanish Mackerel', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Barramundi', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Mangrove Jack', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Giant Trevally', eatingRating: 2, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'],},
        { name: 'Red Emperor', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Queenfish', eatingRating: 3, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Longtail Tuna', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Yellowfin Tuna', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Spangled Emperor', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Cod', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Bream', eatingRating: 3, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Flathead', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Sweetlip Emperor', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Blue Salmon', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    WA: [
        { name: 'Dhufish', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Pink Snapper', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Baldchin Groper', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Coral Trout', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Spanish Mackerel', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Western Rock Lobster', eatingRating: 5, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Samson Fish', eatingRating: 3, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Yellowfin Tuna', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Southern Bluefin Tuna', eatingRating: 5, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Flathead', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Garfish', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Western King Prawn', eatingRating: 5, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Australian Herring', eatingRating: 3, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Yellowtail Kingfish', eatingRating: 4, fightingRating: 5, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Silver Trevally', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    TAS: [
        { name: 'Atlantic Salmon', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Brown Trout', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Rainbow Trout', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Australian Salmon', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Flathead', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Bream', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'King George Whiting', eatingRating: 5, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Black Bream', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Sand Whiting', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Striped Trumpeter', eatingRating: 5, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'],},
        { name: 'Southern Calamari', eatingRating: 5, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Leatherjacket', eatingRating: 3, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Garfish', eatingRating: 4, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Silver Trevally', eatingRating: 3, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Trumpeter', eatingRating: 5, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
    ACT: [
        { name: 'Murray Cod', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Golden Perch', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Brown Trout', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Rainbow Trout', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png' , habitats: ['Estuary', 'Coast', 'Billabong'],},
        { name: 'Redfin Perch', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Carp', eatingRating: 1, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Silver Perch', eatingRating: 3, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Macquarie Perch', eatingRating: 4, fightingRating: 3, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Shortfin Eel', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Mountain Galaxias', eatingRating: 2, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Golden Carp', eatingRating: 1, fightingRating: 1, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Tandanus Catfish', eatingRating: 3, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Silver Carp', eatingRating: 2, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Australian Bass', eatingRating: 4, fightingRating: 4, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
        { name: 'Common Carp', eatingRating: 1, fightingRating: 2, imageUrl: '/images/fish-img.png', habitats: ['Estuary', 'Coast', 'Billabong'], },
    ],
  };
  